STATE_TIME_MORNING = 0
STATE_TIME_AFTERNOON = 1
STATE_TIME_EVENING = 2
STATE_TIME_SLEEPING = 3

STATE_DAY_WEEKDAY = 0
STATE_DAY_WEEKEND = 1

STATE_LOCATION_HOME = 0
STATE_LOCATION_WORK = 1
STATE_LOCATION_OTHER = 2

STATE_ACTIVITY_STATIONARY = 0
STATE_ACTIVITY_WALKING = 1
STATE_ACTIVITY_RUNNING = 2
STATE_ACTIVITY_DRIVING = 3
STATE_ACTIVITY_COMMUTE = 4

STATE_LAST_NOTIFICATION_WITHIN_1HR = 0
STATE_LAST_NOTIFICATION_LONG = 1

ANSWER_NOTIFICATION_DISMISS = 0
ANSWER_NOTIFICATION_IGNORE = 1
ANSWER_NOTIFICATION_ACCEPT = 2
